### ISSUE TITLE
Issue with submission

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/r-py-hw3-asbollapragada#1]
Greetings asbollapragada, 

I am unable to reproduce your submission because the `artists.csv` dataset is not in either a `data` folder, or read in directly from GitHub. Please correct this ASAP (no later than Monday, Nov 6th, 11:59pm). Also, you have two separate yaml configurations at the top of your basic classification .qmd file. Please keep only the second one, since this one aligns with your other .qmd file.

**Comment by asbollapragada** [comment]
Greetings Prof. Greg.

I've corrected them, I tried uploading them before and assumed that they were uploaded successfully but after re checking my submission, I came to know that I am facing issues with my posit cloud account. Hence, I am going to re upload them now because my posit cloud has issues with pushing the files, I had to do it in R studio and upload the files manually. I sincerely apologize for the late submission.
